// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain
#pragma kernel Omissions

struct OmissionModel
{
    float3 posA;
    float3 posB;
    float r;
    float a;
    uint type;
};

int _PositionCount;
RWStructuredBuffer<float3> _Positions;

int _OmissionCount;
RWStructuredBuffer<OmissionModel> _Omissions;

uint _Resolution;
float3 _BoundsMin;
float3 _BoundsMax;
float _Radius;
float _Smooth;
RWTexture3D<float4> _Result;

float Capsule(float3 p, float3 a, float3 b, float r)
{
    float3 pa = p - a;
    float3 ba = b - a;
    float h = saturate(dot(pa,ba)/dot(ba,ba));
    return length(pa - ba*h) - r;
}

inline float SmoothMin(float d1, float d2, float k)
{
    float h = exp(-k * d1) + exp(-k * d2);
    return -log(h) / k;
}

float invLerp(float from, float to, float value) {
    return (value - from) / (to - from);
}

float4 invLerp(float4 from, float4 to, float4 value) {
    return (value - from) / (to - from);
}
float3 invLerp(float3 from, float3 to, float3 value) {
    return (value - from) / (to - from);
}

float Sphere(float3 pos, float radius)
{
    return length(pos) - radius;
}

inline float Box(float3 pos, float3 size)
{
    float3 d = abs(pos) - size;
    return length(max(abs(pos) - size, 0.0))
        + min(max(d.x, max(d.y, d.z)), 0.0);
}

[numthreads(8,8,8)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    if (id.x < _Resolution && id.y < _Resolution && id.z < _Resolution)
    {
        float sdf = 1;
        float halfResolution = _Resolution / 2;
        float3 halfResolution3 = (float3) halfResolution;
        float3 fraction = id / (float3) _Resolution;
        float3 worldPos = lerp(_BoundsMin, _BoundsMax, fraction);
        
        for (int i = 0; i < _PositionCount; i++)
        {
            //float s = Sphere(worldPos - _Positions[i], _Radius);
            float s = Box(worldPos - _Positions[i], _Radius);
            sdf = SmoothMin(sdf, s, _Smooth);
        }

        // find linear parameter from [0, 1] that encodes the SDF value that ranges from [-_Radius, ->]
        float v = invLerp(-_Radius, 0, sdf);

        // find distance fall-off parameter, which will be 0 below 95% and between 0-1 between 95% and 100%
        float t = length(id.xyz - halfResolution3) / halfResolution;
        t = clamp(0, 1, t);
        t = invLerp(0.95, 1, t);
        v = lerp(v, 1, t);
        
        _Result[id.xyz] = float4(v, _Result[id.xyz].g, 0, 1);
    }
}

[numthreads(8,8,8)]
void Omissions (uint3 id : SV_DispatchThreadID)
{
    if (id.x < _Resolution && id.y < _Resolution && id.z < _Resolution)
    {
        float sdf = 0;
        float3 fraction = id / (float3) _Resolution;
        float3 worldPos = lerp(_BoundsMin, _BoundsMax, fraction);

        for (int i = 0; i < _OmissionCount; i++)
        {
            if (_Omissions[i].type == 0)
            {
                float s = Capsule(worldPos, _Omissions[i].posA, _Omissions[i].posB, _Omissions[i].r);
                float t = invLerp(-_Omissions[i].r, 0, s);
                t = clamp(0, 1, t);
                sdf = max(sdf, (1 - t)); 
            }
            else
            {
                float s = Sphere(worldPos - _Omissions[i].posA, _Omissions[i].r);
                float t = invLerp(-_Omissions[i].r, 0, s);
                t = clamp(0, 1, t);
                sdf = max(sdf, (1 - t));
            }
        }

        _Result[id.xyz] = float4(_Result[id.xyz].r, sdf, 0, 1);
    }
}
